[package]
name = "themelios-archive"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
hamu.workspace = true
cp932 = { path = "../cp932" }
