[package]
name = "beryl"
version = "0.1.0"
edition = "2021"

[dependencies]
ansi_term = "0.12.1"
atty = { version = "0.2.14", optional = true }
encoding_rs = { version = "0.8.31", optional = true }
rangemap = "1.0.3"

[features]
default = ["atty", "encoding_rs"]
