[package]
name = "decompress"
version = "0.1.0"
edition = "2021"

[dependencies]
hamu.workspace = true
bitmatch = "0.1.1"
derive_more = { version = "0.99.17", default-features = false, features = ["deref", "deref_mut"] }
thiserror = "1.0.38"
