[package]
name = "calmare"
version = "0.1.0"
edition = "2021"

[dependencies]
themelios = { path = "../themelios" }
strict_result = "1.1.0"
extend = "1.1.2"

unicode-xid = "0.2.4"
codespan-reporting = "0.11.1"
