[package]
name = "calmare"
version = "0.1.0"
edition = "2021"

[dependencies]
themelios.path = "../themelios"
extend = "1.1.2"

unicode-xid = "0.2.4"
glam = "0.24.0"

[dev-dependencies]
codespan-reporting = "0.11.1"
