[package]
name = "themelios-scena"
version = "0.1.0"
edition = "2021"

[dependencies]
gospel.path = "../gospel"
themelios-macros.path = "../themelios-macros"
themelios-common.path = "../themelios-common"

num_enum = "0.5.7"
extend = "1.1.2"
glam = "0.24.0"
