[package]
name = "kiseki"
version = "0.1.0"
edition = "2021"

[dependencies]
choubun = { path = "./choubun" }
kaiseki = { path = "./kaiseki" }

eyre = "0.6.8"
convert_case = "0.5.0"
rocket = "0.5.0-rc.1"
color-eyre = { version = "0.6.1", default-features = false }

[workspace]
members = [
	"hamu",
	"choubun",
	"kaiseki",
]

[profile.dev.package.backtrace]
opt-level = 3
