[package]
name = "kiseki"
version = "0.1.0"
edition = "2021"

[dependencies]
choubun = { path = "./choubun" }
kaiseki = { path = "./kaiseki" }

anyhow = "1.0.56"
convert_case = "0.5.0"
rocket = "0.5.0-rc.1"
