[workspace]
members = [
	"beryl",
	"beryl-cli",
	"hamu",
	"choubun",

	"ed6-macros",
	"ed6",
	"tools",
]

exclude = ["_old"]

[profile.dev]
package.hamu.opt-level = 3
package.choubun.opt-level = 3

package.backtrace.opt-level = 3

package.image.opt-level = 3
package.png.opt-level = 3
package.crc32fast.opt-level = 3
package.deflate.opt-level = 3
package.adler32.opt-level = 3
