[workspace]
members = [
	"choubun",
	"cp932",

	"themelios-macros",
	"themelios",
	"calmare",
	"tools",
]

[profile.dev]
package.hamu.opt-level = 3
package.choubun.opt-level = 3
package.cp932.opt-level = 3

package.backtrace.opt-level = 3

package.image.opt-level = 3
package.png.opt-level = 3
package.crc32fast.opt-level = 3
package.deflate.opt-level = 3
package.adler32.opt-level = 3
