[package]
name = "kiseki"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.56"
hamu = { path = "./hamu" }
mapr = "0.8.0"
chrono = "0.4.19"
thiserror = "1.0.30"
bitmatch = "0.1.1"
int-enum = "0.4.0"
extend = "1.1.2"
itermore = "0.2.0"
encoding_rs = "0.8.31"
bitflags = "1.3.2"
