[package]
name = "roundtrip"
version = "0.1.0"
edition = "2021"

[dependencies]
themelios = { path = "../themelios" }
thiserror = "1.0.0"
test-case = "2.2.1"
lazy_static = "1.4.0"
similar = "2.2.0"
anyhow = "1.0.68"
