[package]
name = "themelios"
version = "0.1.0"
edition = "2021"

[dependencies]
themelios-types.path = "../themelios-types"
themelios-scena.path = "../themelios-scena"
themelios-tables.path = "../themelios-tables"
themelios-archive.path = "../themelios-archive"
