[book]
title = "Aureole Suite"
authors = ["Kyuuhachi", "ShinKiseki"]
language = "en"
multilingual = false
src = "src"

[output.html]
additional-css = ["theme/custom.css"]
additional-js = ["theme/language-calmare.js"]
site-url = "/guide/"
git-repository-url = "https://github.com/Kyuuhachi/Aureole/tree/main/guide"
edit-url-template = "https://github.com/Kyuuhachi/Aureole/edit/main/guide/{path}"
default-theme = "navy"
