[book]
title = "Modding Trails in the Sky for Senior Bracers"
authors = ["ShinKiseki", "Kyuuhachi"]
language = "en"
multilingual = false
src = "src"

[output.html]
additional-css = ["theme/custom.css"]
site-url = "/guide/"
git-repository-url = "https://github.com/Kyuuhachi/Aureole/tree/main/guide"
edit-url-template = "https://github.com/Kyuuhachi/Aureole/edit/main/guide/{path}"
